export { default as Camera } from './Camera'
export { default as Chat } from './Chat'
export { default as Facebook } from './Facebook'
export { default as Gift } from './Gift'
export { default as Instagram } from './Instagram'
export { default as Monitor } from './Monitor'